apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  project: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://github.com/Dayzpd/kustomize-prometheus
    targetRevision: HEAD
    path: overlays/prod
  destination:
    name: prodlab
    namespace: prometheus
  ignoreDifferences: []